### ISSUE TITLE
Option to read from a specific file for tools like tfenv, tofuenv, asdf, etc

### ISSUE THREAD

**Issue by nitrocode** [cloudeteer/actions#8]
Related

- https://github.com/hashicorp/setup-terraform/issues/208

**Comment by rswrz** [comment]
Thanks @nitrocode for opening this issue and suggesting this enhancement. We will discuss this in our next weekly meeting.

**Comment by rswrz** [comment]
### Meeting notes

#### Case 1: default/empty

```yaml
      - name: Get Terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@main
```

First found:

- `required_version` from `*.tf` file (**already implemented**) (version constraint)
- File: `.terraform-version`
- tenv?
- tfenv?
- tofuenv?
- asdf config?
- more?


#### Case 2: specific file

```yaml
      - name: Get Terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@main
        file: file.txt
```

Search for Terraform version only in `file.txt`.

#### Case 3: custom file with custom pattern

```yaml
      - name: Get Terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@main
        file: custom_file.txt
        pattern: ^version: (.*)$
```
---

### Tasks

1. Implement `.terraform-version`
2. Implement custom pattern
3. Implement built-in pattern for `tenv`, `tfenv`, `tofuenv`, `asdf` configuration files
